version: 2
project_name: kuang

builds:
  - id: kuang
    main: ./cmd/app
    binary: kuang
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}

archives:
  - id: binary
    builds:
      - kuang
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

changelog:
  use: github
  sort: asc
  groups:
    - title: "Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
    - title: "Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
    - title: "Performance"
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: zoobzio
    name: kuang
  draft: false
  prerelease: auto
